baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "RUAX的博客"
theme = "ananke"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4